CREATE INDEX wwv_mig_olb_cg_ct_ts_ct_id_idx ON wwv_mig_olb_cg_ct_textsegment(compoundtext_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";