CREATE INDEX wwv_flow_worksheet_hist_01 ON wwv_flow_worksheet_history(worksheet_id,row_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";