CREATE INDEX wwv_flow_lang_comp_idx1 ON wwv_flow_languages(lang_id_upper,"NLS_LANGUAGE","NLS_TERRITORY")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";