CREATE UNIQUE INDEX wwv_flow_prov_company_admin_id ON wwv_flow_provision_company(admin_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";