CREATE INDEX wwv_mig_acc_rel_idx3 ON wwv_mig_acc_relations(project_id,dbid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";