CREATE INDEX wwv_flow_build_audit_trail_i3 ON wwv_flow_builder_audit_trail(flow_id,security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";