CREATE INDEX wwv_flow_entry_point_arg_idx2 ON wwv_flow_entry_point_args(flow_entry_point_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";