CREATE UNIQUE INDEX wwv_flow_list_items_idx2 ON wwv_flow_list_items(list_id,"ID",item_displayed,required_patch)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";