CREATE UNIQUE INDEX wwv_flow_app_build_pref_idx1 ON wwv_flow_app_build_pref(security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";