CREATE INDEX wwv_mig_grp_item_id_idx ON wwv_mig_rpt_grp_dataitem("GROUP_ID")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";