CREATE UNIQUE INDEX wwv_flow_tmps_unique ON wwv_flow_templates$(template_name)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";