CREATE INDEX wwv_mig_acc_form_ctl_idx1 ON wwv_mig_acc_forms_controls(formid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";