CREATE INDEX wwv_mig_olb_t_tp_gggg_sgid_idx ON wwv_mig_olb_t_tp_ggg_graphics(security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";