CREATE INDEX wwv_mig_mnu_modrole_id_idx ON wwv_mig_frm_menusmoduleroles(menumodule_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";