CREATE INDEX wwv_flow_prov_company_mod_idx1 ON wwv_flow_provision_serice_mod(security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";