CREATE UNIQUE INDEX wwv_flow_entry_points_idx2 ON wwv_flow_entry_points(flow_id,security_group_id,"NAME")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";