CREATE INDEX wwv_flow_worksheet_links_idx1 ON wwv_flow_worksheet_links(row_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";