CREATE INDEX wwv_flow_translatable_substr ON wwv_flow_translatable_text$(text_substr_1_255)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";