CREATE INDEX wwv_flow_css_repository_fkidx ON wwv_flow_css_repository(security_group_id,"ID")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";