CREATE INDEX wwv_mig_rpt_datasum_id_idx ON wwv_mig_rpt_data_summary(data_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";