CREATE INDEX wwv_flow_mp_parent_page_idx ON wwv_flow_model_pages(parent_page_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";