CREATE INDEX wwv_flow_sqry_sql_fk1 ON wwv_flow_shared_qry_sql_stmts(flow_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";