CREATE INDEX wwv_flow_activity_log1$_idx1 ON wwv_flow_activity_log1$(time_stamp)
NOCOMPRESS
PCTFREE 10 INITRANS 8 LOGGING
STORAGE(INITIAL 106496 NEXT 106496
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";