CREATE INDEX wwv_flow_web_pg_list_ent_idx1 ON wwv_flow_web_pg_list_entries(region_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";