CREATE INDEX wwv_flow_css_upper_name ON wwv_flow_css_repository(upper_css_name)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";