CREATE UNIQUE INDEX wwv_flow_data_idx1 ON wwv_flow_data(flow_instance,item_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";