CREATE INDEX wwv_mig_olb_ttp5gcts_sg_id_ix ON wwv_mig_olb_t_tp_ggggg_ct_txst(security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";