CREATE UNIQUE INDEX wwv_mig_rev_frm_uk1 ON wwv_mig_rev_forms(project_id,dbid,formid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";