CREATE INDEX wwv_mig_olb_ttp5gcts_ct_id_ix ON wwv_mig_olb_t_tp_ggggg_ct_txst(compoundtext_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";