CREATE INDEX wwv_flow_install_build_idx4 ON wwv_flow_install_build_opt(build_opt_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";