CREATE INDEX wwv_flow_required_roles_fkidx ON wwv_flow_required_roles(flow_id,role_name)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";