CREATE UNIQUE INDEX wwv_flow_import_export_fkidx2 ON wwv_flow_import_export(security_group_id,data_id,"ID")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";