CREATE INDEX wwv_flow_lock_page_log_i1 ON wwv_flow_lock_page_log(lock_flow)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";