CREATE UNIQUE INDEX wwv_flow_install_scripts_idx1 ON wwv_flow_install_scripts(flow_id,"NAME",script_type)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";