CREATE INDEX wwv_mig_olb_pc_objlibid_idx ON wwv_mig_olb_propertyclass(objectlibrary_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";