CREATE INDEX wwv_mig_acc_rep_ctl_idx1 ON wwv_mig_acc_rpts_controls(reportid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";