CREATE INDEX wwv_flow_mail_log_idx1 ON wwv_flow_mail_log(SUBSTR("MAIL_TO",1,500))
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";