CREATE UNIQUE INDEX wwv_flow_chart_seattr_idx ON wwv_flow_region_chart_ser_attr(region_id,series_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";