CREATE UNIQUE INDEX wwv_flow_image_reposito_fkidx ON wwv_flow_image_repository(security_group_id,flow_id,"ID")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";