CREATE INDEX wwv_flow_shared_web_serv_idx1 ON wwv_flow_shared_web_services(flow_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";