CREATE UNIQUE INDEX wwv_flow_fnd_group_users_i2 ON wwv_flow_fnd_group_users(user_id,"GROUP_ID")
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";