CREATE INDEX wwv_flow_mpc_mp_idx ON wwv_flow_model_page_cols(model_region_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";