CREATE UNIQUE INDEX wwv_flow_stored_queries_uk1 ON wwv_flow_shared_queries("NAME",flow_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";