CREATE INDEX wwv_flow_page_cache_idx2 ON wwv_flow_page_cache(region_id,flow_id,page_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";