CREATE UNIQUE INDEX wwv_flow_lock_page_pg ON wwv_flow_lock_page(object_id,flow_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";