CREATE UNIQUE INDEX wwv_flow_worksheets_unq_idx ON wwv_flow_worksheets(CASE  WHEN "REGION_ID" IS NULL THEN "FLOW_ID" END,CASE  WHEN "REGION_ID" IS NULL THEN "OWNER" END,CASE  WHEN "REGION_ID" IS NULL THEN "FOLDER_ID" END,CASE  WHEN "REGION_ID" IS NULL THEN "NAME" END)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";