CREATE INDEX wwv_mig_olb_bil_itm_id_idx ON wwv_mig_olb_blk_item_lie(item_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";