CREATE UNIQUE INDEX wwv_flow_report_layouts_idx2 ON wwv_flow_report_layouts(flow_id,SUBSTR("REPORT_LAYOUT_NAME",1,500))
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";