CREATE INDEX wwv_flow_image_repo_idx3 ON wwv_flow_image_repository(is_on_filesystem)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";