CREATE INDEX wwv_mig_acc_index_idx2 ON wwv_mig_acc_indexes(project_id,dbid,tblid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";