CREATE UNIQUE INDEX wwv_flow_worksheet_rpts_uk ON wwv_flow_worksheet_rpts(CASE  WHEN "SESSION_ID" IS NULL THEN "WORKSHEET_ID" END,CASE  WHEN "SESSION_ID" IS NULL THEN "APPLICATION_USER" END,CASE  WHEN "SESSION_ID" IS NULL THEN "CATEGORY_ID" END,CASE  WHEN "SESSION_ID" IS NULL THEN "NAME" END)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";