CREATE INDEX wwv_mig_proj_trig_pj_id_idx ON wwv_mig_project_triggers(project_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";