CREATE INDEX wwv_mig_accrelcol_idx2 ON wwv_mig_acc_relation_cols(project_id,dbid,relid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";