CREATE INDEX wwv_mig_olb_t_tp_ggg_g_id_idx ON wwv_mig_olb_t_tp_gg_graphics(graphics_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";