CREATE INDEX wwv_mig_olb_ttp4gcts_sg_id_idx ON wwv_mig_olb_t_tp_gggg_ct_txsgt(security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";