CREATE INDEX wwv_mig_olb_blk_item_blkid_idx ON wwv_mig_olb_blk_item(block_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";