CREATE INDEX wwv_mig_gen_app_proj_id_idx ON wwv_mig_generated_applications(project_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";