CREATE INDEX wwv_flow_pages_reserved_idx ON wwv_flow_pages_reserved(created_on)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";