CREATE INDEX wwv_flow_pref_user_pref_idx ON wwv_flow_preferences$(user_id,preference_name)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(INITIAL 106496 NEXT 106496
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";