CREATE INDEX wwv_flow_ws_comp_cols_idx ON wwv_flow_worksheet_computation(worksheet_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";