CREATE INDEX wwv_flow_mpr_model_idx ON wwv_flow_model_page_regions(model_page_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";