CREATE UNIQUE INDEX wwv_biu_fl_alt_config_idx1 ON wwv_flow_alternate_config(flow_id,"NAME",security_group_id)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";