CREATE INDEX wwv_flow_page_cache_idx1 ON wwv_flow_page_cache(flow_id,page_id,language,context1)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";