CREATE UNIQUE INDEX wwv_flow_worksheet_cond_uk2 ON wwv_flow_worksheet_conditions(report_id,SUBSTR("CONDITION_TYPE",1,30),SUBSTR("COLUMN_NAME",1,30),"OPERATOR",SUBSTR("EXPR",1,250),SUBSTR("EXPR2",1,100))
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";