CREATE INDEX wwv_mig_rev_apexapp_idx1 ON wwv_mig_rev_apexapp(project_id,dbid)
NOCOMPRESS
PCTFREE 10 INITRANS 2 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";