GRANT ALTER ON oc_michael_a.job_history TO scott;
GRANT DEBUG ON oc_michael_a.job_history TO scott;
GRANT DELETE ON oc_michael_a.job_history TO scott;
GRANT FLASHBACK ON oc_michael_a.job_history TO scott;
GRANT INDEX ON oc_michael_a.job_history TO scott;
GRANT INSERT ON oc_michael_a.job_history TO scott;
GRANT ON COMMIT REFRESH ON oc_michael_a.job_history TO scott;
GRANT QUERY REWRITE ON oc_michael_a.job_history TO scott;
GRANT REFERENCES ON oc_michael_a.job_history TO scott;
GRANT SELECT ON oc_michael_a.job_history TO oe;
GRANT SELECT ON oc_michael_a.job_history TO scott;
GRANT UPDATE ON oc_michael_a.job_history TO scott;