CREATE TABLE rel_18_a_12c2.odc_350 (
  key_col NUMBER(12) NOT NULL,
  "T" TIMESTAMP(3),
  tz TIMESTAMP(3) WITH TIME ZONE,
  tlz TIMESTAMP(3) WITH LOCAL TIME ZONE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT odc_350_pk PRIMARY KEY (key_col,tlz)
);