GRANT ALTER ON matthew_a.departments TO scott;
GRANT DEBUG ON matthew_a.departments TO scott;
GRANT DELETE ON matthew_a.departments TO scott;
GRANT FLASHBACK ON matthew_a.departments TO scott;
GRANT INDEX ON matthew_a.departments TO scott;
GRANT INSERT ON matthew_a.departments TO scott;
GRANT ON COMMIT REFRESH ON matthew_a.departments TO scott;
GRANT QUERY REWRITE ON matthew_a.departments TO scott;
GRANT REFERENCES ON matthew_a.departments TO scott;
GRANT SELECT ON matthew_a.departments TO oe;
GRANT SELECT ON matthew_a.departments TO scott;
GRANT UPDATE ON matthew_a.departments TO scott;