GRANT ALTER ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT DELETE ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT FLASHBACK ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT INDEX ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT INSERT ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT ON COMMIT REFRESH ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT QUERY REWRITE ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT REFERENCES ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT SELECT ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;
GRANT UPDATE ON flows_files.wwv_flow_file_objects$ TO apex_030200 WITH GRANT OPTION;