CREATE MATERIALIZED VIEW rel_18_a_12c2.build_mode_different (answer,nottheanswer)
ORGANIZATION HEAP 
BUILD DEFERRED
AS SELECT "MASTER_TABLE"."ANSWER" "ANSWER","MASTER_TABLE"."NOTTHEANSWER" "NOTTHEANSWER" FROM rel_18_a_12c2."MASTER_TABLE" "MASTER_TABLE";