CREATE MATERIALIZED VIEW rel_18_a_12c2.next_different (answer,nottheanswer)
ORGANIZATION HEAP 
REFRESH START WITH TO_DATE('2017-5-8 8:42:43', 'yyyy-mm-dd hh24:mi:ss') NEXT sysdate + 3 
AS SELECT "MASTER_TABLE"."ANSWER" "ANSWER","MASTER_TABLE"."NOTTHEANSWER" "NOTTHEANSWER" FROM rel_18_a_12c2."MASTER_TABLE" "MASTER_TABLE";