CREATE MATERIALIZED VIEW rel_18_a_12c2.parallel_num_different (answer,nottheanswer)
ORGANIZATION HEAP 
PARALLEL 20
AS SELECT "MASTER_TABLE"."ANSWER" "ANSWER","MASTER_TABLE"."NOTTHEANSWER" "NOTTHEANSWER" FROM rel_18_a_12c2."MASTER_TABLE" "MASTER_TABLE";