CREATE TABLE oc_michael_a.nlstest (
  "OWNER" VARCHAR2(128 BYTE),
  object_name VARCHAR2(128 BYTE),
  subobject_name VARCHAR2(128 BYTE),
  object_id NUMBER,
  data_object_id NUMBER,
  object_type VARCHAR2(23 BYTE),
  created DATE,
  last_ddl_time DATE,
  "TIMESTAMP" VARCHAR2(19 BYTE),
  status VARCHAR2(7 BYTE),
  "TEMPORARY" VARCHAR2(1 BYTE),
  "GENERATED" VARCHAR2(1 BYTE),
  secondary VARCHAR2(1 BYTE),
  "NAMESPACE" NUMBER,
  edition_name VARCHAR2(128 BYTE),
  "SHARING" VARCHAR2(18 BYTE),
  "EDITIONABLE" VARCHAR2(1 BYTE),
  oracle_maintained VARCHAR2(1 BYTE),
  "APPLICATION" VARCHAR2(1 BYTE),
  default_collation VARCHAR2(100 BYTE),
  duplicated VARCHAR2(1 BYTE),
  sharded VARCHAR2(1 BYTE),
  created_appid NUMBER,
  created_vsnid NUMBER,
  modified_appid NUMBER,
  modified_vsnid NUMBER,
  qwerty NUMBER
);