CREATE TABLE table1 (
  col1 NUMBER(10) NOT NULL,
  col2 NUMBER(10),
  CONSTRAINT col1_pk PRIMARY KEY (col1) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSTEM"
) NOCOMPRESS
PCTFREE 10 PCTUSED 40 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSTEM";