CREATE MATERIALIZED VIEW oc_michael_b.build_mode_different (answer,nottheanswer)
ORGANIZATION HEAP 
BUILD DEFERRED
AS SELECT "MASTER_TABLE"."ANSWER" "ANSWER","MASTER_TABLE"."NOTTHEANSWER" "NOTTHEANSWER" FROM oc_michael_b."MASTER_TABLE" "MASTER_TABLE";