CREATE MATERIALIZED VIEW oc_michael_b.mv_more_then_one_primary_key (col1,col2,col3)
ORGANIZATION HEAP 
AS SELECT "MORE_THEN_ONE_PRIMARY_KEY"."COL1" "COL1","MORE_THEN_ONE_PRIMARY_KEY"."COL2" "COL2","MORE_THEN_ONE_PRIMARY_KEY"."COL3" "COL3" FROM oc_michael_b."MORE_THEN_ONE_PRIMARY_KEY" "MORE_THEN_ONE_PRIMARY_KEY";