CREATE MATERIALIZED VIEW oc_michael_b.never_refresh_alter_different (answer,nottheanswer)
ORGANIZATION HEAP 
NEVER REFRESH 
AS SELECT "MASTER_TABLE"."ANSWER" "ANSWER","MASTER_TABLE"."NOTTHEANSWER" "NOTTHEANSWER" FROM oc_michael_b."MASTER_TABLE" "MASTER_TABLE";