CREATE MATERIALIZED VIEW oc_michael_b.parallel_different_rev (answer,nottheanswer)
ORGANIZATION HEAP 
PARALLEL
AS SELECT "MASTER_TABLE"."ANSWER" "ANSWER","MASTER_TABLE"."NOTTHEANSWER" "NOTTHEANSWER" FROM oc_michael_b."MASTER_TABLE" "MASTER_TABLE";