CREATE TABLE wwv_flow_pick_database_size (
  "ID" NUMBER NOT NULL,
  db_size VARCHAR2(30 BYTE) NOT NULL,
  db_size_desc VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT wwv_flow_pick_db_size_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";