CREATE TABLE wwv_flow_template_themes$ (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(255 BYTE),
  required_css VARCHAR2(255 BYTE),
  CONSTRAINT wwv_fl_tmp_thm_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";