CREATE TABLE wwv_flow_security_schemes (
  "ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  scheme_type VARCHAR2(255 BYTE),
  scheme VARCHAR2(4000 BYTE) NOT NULL,
  scheme_text VARCHAR2(4000 BYTE),
  error_message VARCHAR2(4000 BYTE) NOT NULL,
  "CACHING" VARCHAR2(255 BYTE) CONSTRAINT wwv_flow_sec_scheme_cache CHECK ("CACHING" in (
                              'BY_USER_BY_PAGE_VIEW',
                              'BY_USER_BY_SESSION')),
  reference_id NUMBER,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  comments VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_sec_scheme_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_sec_schemes_fk FOREIGN KEY (flow_id) REFERENCES wwv_flows ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";