CREATE TABLE wwv_flow_pages_reserved (
  "ID" NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  flow_session NUMBER,
  created_on DATE,
  created_by VARCHAR2(255 BYTE),
  CONSTRAINT wwv_flow_pages_reserved_pk PRIMARY KEY ("ID",flow_id) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_pages_reserved_fk FOREIGN KEY (flow_id) REFERENCES wwv_flows ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";