CREATE TABLE wwv_flow_workspace_req_size (
  "ID" NUMBER NOT NULL,
  request_type VARCHAR2(1 BYTE) NOT NULL CONSTRAINT wwv_flow_wksp_request_type CHECK (request_type in ('N','C')),
  req_size VARCHAR2(30 BYTE) NOT NULL,
  display VARCHAR2(1 BYTE) NOT NULL CONSTRAINT wwv_flow_wksp_req_size_display CHECK (display in ('Y','N')),
  default_size VARCHAR2(1 BYTE) NOT NULL CONSTRAINT wwv_flow_wksp_req_size_default CHECK (default_size in ('Y','N')),
  CONSTRAINT wwv_flow_workspace_req_size_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";