CREATE TABLE wwv_flow_request_verifications (
  session_id NUMBER NOT NULL,
  verification_string VARCHAR2(100 BYTE) NOT NULL,
  CONSTRAINT wwv_flow_request_verif_pk PRIMARY KEY (session_id) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_request_verif_fk FOREIGN KEY (session_id) REFERENCES wwv_flow_sessions$ ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";