CREATE TABLE wwv_flow_data (
  flow_instance NUMBER NOT NULL,
  item_id NUMBER,
  item_element_id NUMBER,
  item_filter VARCHAR2(1 BYTE) CONSTRAINT valid_item_filter CHECK (item_filter in ('Y','N')),
  session_state_status VARCHAR2(1 BYTE) CONSTRAINT valid_session_state_status CHECK (session_state_status in ('I','U','R')),
  flow_id NUMBER,
  item_name VARCHAR2(255 BYTE),
  name_length NUMBER(*,0),
  is_encrypted VARCHAR2(1 BYTE),
  item_value CLOB,
  CONSTRAINT wwv_flow_data_fk FOREIGN KEY (flow_instance) REFERENCES wwv_flow_sessions$ ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 1048576 NEXT 1048576
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX"
LOB (item_value) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  CACHE READS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));