CREATE TABLE wwv_flow_sw_stmts (
  "ID" NUMBER NOT NULL,
  file_id NUMBER NOT NULL,
  stmt_number NUMBER,
  src_line_number NUMBER,
  "OFFSET" NUMBER,
  "LENGTH" NUMBER,
  stmt_class NUMBER,
  stmt_id NUMBER,
  isrunnable VARCHAR2(1 BYTE),
  stmt CLOB,
  security_group_id NUMBER NOT NULL,
  CONSTRAINT wwv_flow_sw_stmts_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_sw_stmts_fk2 FOREIGN KEY (security_group_id) REFERENCES wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX"
LOB (stmt) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));