CREATE TABLE wwv_flow_upg_tab_name_changes (
  old_table_name VARCHAR2(30 BYTE) NOT NULL,
  new_table_name VARCHAR2(30 BYTE) NOT NULL,
  change_date DATE NOT NULL,
  change_made VARCHAR2(1 BYTE) NOT NULL CONSTRAINT wwv_flow_upg_tab_name_chg_done CHECK (change_made in ('Y','N')),
  CONSTRAINT wwv_flow_upg_tab_name_chng_pk PRIMARY KEY (old_table_name) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_upg_tab_name_chng_uk UNIQUE (new_table_name) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";