CREATE TABLE wwv_flow_template_preferences (
  "OWNER" VARCHAR2(30 BYTE) NOT NULL,
  flow_id NUMBER NOT NULL,
  template_preference VARCHAR2(120 BYTE),
  printer_template_preference VARCHAR2(120 BYTE),
  security_group_id NUMBER NOT NULL,
  CONSTRAINT wwv_flow_templ_pref_pk PRIMARY KEY ("OWNER") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_templ_pref_fk FOREIGN KEY (flow_id) REFERENCES wwv_flows ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";