CREATE TABLE wwv_flow_online_help_ja (
  "ID" NUMBER NOT NULL,
  url VARCHAR2(4000 BYTE) NOT NULL,
  filename VARCHAR2(4000 BYTE) NOT NULL,
  title VARCHAR2(4000 BYTE) NOT NULL,
  cset VARCHAR2(100 BYTE) NOT NULL,
  plaintext CLOB,
  CONSTRAINT wwv_flow_online_help_ja_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX"
LOB (plaintext) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));