CREATE TABLE wwv_flow_file_objects$part (
  "DOCUMENT" VARCHAR2(350 BYTE) NOT NULL,
  part VARCHAR2(350 BYTE) NOT NULL,
  uploaded CHAR
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";