CREATE TABLE wwv_flow_translatable_cols$ (
  "ID" NUMBER NOT NULL,
  table_name VARCHAR2(30 BYTE),
  column_name VARCHAR2(30 BYTE),
  table_pk VARCHAR2(30 BYTE),
  flow_id_column VARCHAR2(30 BYTE),
  page_id_column VARCHAR2(30 BYTE),
  datatype VARCHAR2(30 BYTE),
  template_translatable VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_trans_cols_chk CHECK (template_translatable in ('Y','N')),
  column_description VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_trans_cols_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";