CREATE TABLE wwv_flow_debug (
  "ID" NUMBER,
  seq NUMBER,
  message VARCHAR2(4000 BYTE)
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";