CREATE TABLE wwv_flow_page_submissions (
  submit_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  page_id NUMBER,
  session_id NUMBER,
  CONSTRAINT wwv_flow_page_submissions_pk PRIMARY KEY (submit_id) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_page_sub_fk FOREIGN KEY (flow_id) REFERENCES wwv_flows ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";