CREATE TABLE wwv_flow_shared_web_services (
  "ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  flow_id NUMBER,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  url VARCHAR2(4000 BYTE),
  "ACTION" VARCHAR2(4000 BYTE),
  proxy_override VARCHAR2(4000 BYTE),
  soap_envelope CLOB,
  flow_items_comma_delimited CLOB,
  static_parm_01 VARCHAR2(4000 BYTE),
  static_parm_02 VARCHAR2(4000 BYTE),
  static_parm_03 VARCHAR2(4000 BYTE),
  static_parm_04 VARCHAR2(4000 BYTE),
  static_parm_05 VARCHAR2(4000 BYTE),
  static_parm_06 VARCHAR2(4000 BYTE),
  static_parm_07 VARCHAR2(4000 BYTE),
  static_parm_08 VARCHAR2(4000 BYTE),
  static_parm_09 VARCHAR2(4000 BYTE),
  static_parm_10 VARCHAR2(4000 BYTE),
  stylesheet CLOB,
  reference_id NUMBER,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  CONSTRAINT wwv_flow_web_services_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_ws_fk FOREIGN KEY (flow_id) REFERENCES wwv_flows ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX"
LOB (flow_items_comma_delimited) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
LOB (soap_envelope) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  CACHE READS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
LOB (stylesheet) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  CACHE READS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
COMMENT ON COLUMN wwv_flow_shared_web_services.url IS 'SOAP Service URL';
COMMENT ON COLUMN wwv_flow_shared_web_services."ACTION" IS 'SOAP Action';
COMMENT ON COLUMN wwv_flow_shared_web_services.proxy_override IS 'HTTP proxy for SOAP request';
COMMENT ON COLUMN wwv_flow_shared_web_services.soap_envelope IS 'May contain #ITEM_NAME# substitutions';
COMMENT ON COLUMN wwv_flow_shared_web_services.flow_items_comma_delimited IS 'A comma delmited list of flow items contained in the body for example: ITEM1,ITEM2,ITEM3';