CREATE TABLE wwv_flow_query_column (
  "ID" NUMBER NOT NULL,
  query_id NUMBER NOT NULL,
  query_object_id NUMBER,
  column_number NUMBER NOT NULL,
  column_alias VARCHAR2(255 BYTE) NOT NULL,
  column_sql_expression VARCHAR2(4000 BYTE) NOT NULL,
  column_group_by_sequence NUMBER,
  security_group_id NUMBER NOT NULL,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  CONSTRAINT query_column_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT query_column_to_qry_object_fk FOREIGN KEY (query_object_id) REFERENCES wwv_flow_query_object ("ID") ON DELETE CASCADE,
  CONSTRAINT query_column_to_query_fk FOREIGN KEY (query_id) REFERENCES wwv_flow_query_definition ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";