CREATE TABLE wwv_mig_exporter (
  "ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  filename VARCHAR2(2000 BYTE) NOT NULL,
  description VARCHAR2(1000 BYTE),
  access_version NUMBER,
  exporter_version VARCHAR2(100 BYTE),
  CONSTRAINT wwv_mig_exporter_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_mig_exporter_fk FOREIGN KEY (security_group_id) REFERENCES wwv_flow_companies (provisioning_company_id)
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";