CREATE TABLE wwv_column_exceptions (
  table_name VARCHAR2(40 BYTE) NOT NULL,
  column_name VARCHAR2(40 BYTE) NOT NULL,
  obsolete_date DATE DEFAULT null,
  CONSTRAINT col_exceptions_pk PRIMARY KEY (table_name,column_name) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX"
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";