CREATE TABLE wwv_flow_qb_saved_tabs (
  "ID" NUMBER NOT NULL,
  "OID" NUMBER NOT NULL,
  cnt NUMBER NOT NULL,
  top VARCHAR2(255 BYTE),
  "LEFT" VARCHAR2(255 BYTE),
  tname VARCHAR2(255 BYTE) NOT NULL,
  security_group_id NUMBER NOT NULL,
  CONSTRAINT pk_wwv_flow_qb_saved_tabs PRIMARY KEY ("ID","OID",cnt) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  FOREIGN KEY ("ID") REFERENCES wwv_flow_qb_saved_query ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";