CREATE TABLE wwv_flow_clickthru_log2$ (
  clickdate DATE,
  "CATEGORY" VARCHAR2(255 BYTE),
  "ID" NUMBER,
  flow_user VARCHAR2(255 BYTE),
  ip VARCHAR2(30 BYTE),
  security_group_id NUMBER NOT NULL
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";