CREATE TABLE wwv_flow_worksheet_lov_entries (
  "ID" NUMBER NOT NULL,
  worksheet_id NUMBER NOT NULL,
  lov_id NUMBER NOT NULL,
  display_sequence NUMBER NOT NULL,
  entry_text VARCHAR2(255 BYTE) NOT NULL,
  created_on DATE NOT NULL,
  created_by VARCHAR2(255 BYTE) NOT NULL,
  updated_on DATE,
  updated_by VARCHAR2(255 BYTE),
  security_group_id NUMBER NOT NULL,
  CONSTRAINT wwv_flow_worksheet_lov_ent_pk PRIMARY KEY ("ID") USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_ws_lov_ents_uk UNIQUE (lov_id,entry_text) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
    STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "SYSAUX",
  CONSTRAINT wwv_flow_worksheet_lov_ent_fk FOREIGN KEY (worksheet_id) REFERENCES wwv_flow_worksheets ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_flow_worksheet_lov_ent_fk2 FOREIGN KEY (lov_id) REFERENCES wwv_flow_worksheet_lovs ("ID") ON DELETE CASCADE
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";