CREATE TABLE wwv_flow_clickthru_log_number$ (
  current_log_number NUMBER NOT NULL CHECK (current_log_number in (1,2)),
  current_log_timestamp DATE NOT NULL,
  minimum_retained_days NUMBER NOT NULL
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "SYSAUX";